version: '2'

services:
  # This container is never builded - it's used only
  # for reusing configuration,
  meta:
    image: busybox # Necessary to make this container valid.
    environment:
      - MYSQL_USER=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  drupal:
    extends: meta
    image: natura-poc-drupal # Only needed to override "meta" image.
    build:
      context: ./drupal/docker/
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    hostname: drupal
    ports:
      - "80:80"
    cap_add:
      - ALL
    links:
      - database:database-host
    volumes:
        # 1 - Use ssh config from host.
        # 2 - Use git config from host.
        # 3 - Place app files.
      - $HOME/.ssh:/drupal/.ssh
      - $HOME/.gitconfig:/drupal/.gitconfig
      - $PWD/drupal:/drupal

  database:
    extends: meta
    image: mysql:5.6
    container_name: natura-poc-db
    # volumes:
      # Persist database outside container.
      # @TODO: this does not work on docker-machine, and therefore it's commented out so
      # to avoid misleading behavior on that environment. Everything works just fine
      # without this mounted volume, but database wont persist after you shutdown the
      # database container.
      # - $PWD/.mysql/:/var/lib/mysql
